import Image from "next/image"
import Link from "next/link"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faArrowRight } from "@fortawesome/free-solid-svg-icons"
import { rooms } from "@/lib/rooms"

export function GalleryGrid() {
  return (
    <div>
      <section id="spaces" className="bg-cream py-24 md:py-36"><div className="mx-auto max-w-[1320px] px-5 md:px-10"><div className="mb-14 grid gap-8 lg:grid-cols-2 lg:items-end"><div><p className="mb-5 font-sans text-xs font-semibold uppercase tracking-[.24em] text-terracotta">01 · The spaces</p><h2 className="text-balance font-serif text-5xl font-light leading-[1.02] md:text-7xl">A house open to light and sky.</h2></div><p className="max-w-lg text-pretty font-sans text-base leading-7 text-midnight-blue/75 lg:justify-self-end">From the stillness of the courtyard to the openness of the roof, Dar Ten changes character as you move through it.</p></div><div className="grid gap-4 md:grid-cols-12"><figure className="relative min-h-[640px] md:col-span-7"><Image src="/assets/images/home/welcome.png" alt="Sunlit central courtyard and pool" fill sizes="(max-width: 768px) 100vw, 58vw" className="object-cover" /></figure><div className="grid gap-4 md:col-span-5"><figure className="relative min-h-[310px]"><Image src="/assets/images/gallery/ground-floor.png" alt="Ground-floor arches around the patio" fill sizes="(max-width: 768px) 100vw, 42vw" className="object-cover" /></figure><figure className="relative min-h-[310px]"><Image src="/assets/images/gallery/pool-night.png" alt="Courtyard pool illuminated after dark" fill sizes="(max-width: 768px) 100vw, 42vw" className="object-cover" /></figure></div></div></div></section>

      <section className="bg-midnight-blue py-24 text-cream md:py-36"><div className="mx-auto max-w-[1440px] px-5 md:px-10"><div className="mb-14 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-5 font-sans text-xs font-semibold uppercase tracking-[.24em] text-saffron-gold">02 · The rooms</p><h2 className="text-balance font-serif text-5xl font-light leading-[1.02] md:text-7xl">Six names. Six moods.</h2></div><Link href="/rooms" className="group inline-flex min-h-11 items-center gap-3 self-start border-b border-cream/40 font-sans text-xs uppercase tracking-[.18em] hover:border-cream md:self-auto">Explore every room <FontAwesomeIcon icon={faArrowRight} className="size-3 transition-transform group-hover:translate-x-1" /></Link></div><div className="grid gap-x-4 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{rooms.map((room, index) => <Link key={room.slug} href={`/rooms/${room.slug}`} className={`group block ${index % 3 === 1 ? "lg:mt-20" : ""}`}><figure className="relative aspect-[4/5] overflow-hidden"><Image src={room.image} alt={`${room.name} double room`} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.035]" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent" /><figcaption className="absolute inset-x-0 bottom-0 p-6 font-serif text-4xl font-light text-white">{room.name}</figcaption></figure><p className="mt-4 text-pretty font-sans text-base leading-7 text-cream/75">{room.tone}</p></Link>)}</div></div></section>

      <section className="bg-[#e7ddcf] py-24 md:py-36"><div className="mx-auto max-w-[1320px] px-5 md:px-10"><div className="mb-14 max-w-3xl"><p className="mb-5 font-sans text-xs font-semibold uppercase tracking-[.24em] text-terracotta">03 · A day at Dar Ten</p><h2 className="text-balance font-serif text-5xl font-light leading-[1.02] md:text-7xl">Breakfast, warm stone and evenings by the water.</h2></div><div className="grid gap-4 md:grid-cols-12"><figure className="relative min-h-[540px] md:col-span-5 md:mt-28"><Image src="/assets/images/riad/food/breakfast-03.png" alt="Homemade breakfast at Dar Ten" fill sizes="(max-width: 768px) 100vw, 42vw" className="object-cover" /><figcaption className="absolute bottom-0 left-0 bg-cream px-5 py-3 font-sans text-xs uppercase tracking-[.18em]">Morning</figcaption></figure><figure className="relative min-h-[680px] md:col-span-7"><Image src="/assets/images/gallery/dinner-pool-night.png" alt="Dinner table set beside the courtyard pool" fill sizes="(max-width: 768px) 100vw, 58vw" className="object-cover" /><figcaption className="absolute bottom-0 left-0 bg-cream px-5 py-3 font-sans text-xs uppercase tracking-[.18em]">Evening</figcaption></figure></div></div></section>
    </div>
  )
}
